services:
  - type: web
    name: okn-controller-ws
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    root: laptop-controller
    envVars:
      - key: NODE_ENV
        value: production
